# Jekyll configuration

name: dounaiKing
description: Welcome to dounaiKing's world！

# url is currently only used only for the RSS feed in feed.xml
url: https://github.com/zxixia/jekyll-xixia

# baseurl will often be '', but for a project page on gh-pages, it needs to
# be the project name.
# *** IMPORTANT: If your local "jekyll serve" throws errors change this to '' or
#     run it like so: jekyll serve --baseurl=''
baseurl: ''
## default date_format
date_format: 
  title: "%B-%-d-%Y"
  archive: "%b"
  categories: "%b-%Y"
  tag: "%b-%Y"
# Language
lan: "en" 

# 开启评论
comments: true
gitment: on

paginate: 10

highlighter: rouge
markdown: kramdown
gems: ['jekyll-paginate']

exclude: ['README.md', 'LICENSE', "*.bak"]
